/**
 * Maps IANA timezone strings to country names.
 * Used to infer a lead's country from their browser timezone.
 */

const timezoneToCountry: Record<string, string> = {
  // North America
  "America/New_York": "United States",
  "America/Chicago": "United States",
  "America/Denver": "United States",
  "America/Los_Angeles": "United States",
  "America/Phoenix": "United States",
  "America/Anchorage": "United States",
  "Pacific/Honolulu": "United States",
  "America/Detroit": "United States",
  "America/Indiana/Indianapolis": "United States",
  "America/Boise": "United States",
  "America/Juneau": "United States",
  "America/Adak": "United States",
  "America/Nome": "United States",
  "America/Sitka": "United States",
  "America/Yakutat": "United States",
  "America/Metlakatla": "United States",
  "America/Kentucky/Louisville": "United States",
  "America/Kentucky/Monticello": "United States",
  "America/Indiana/Knox": "United States",
  "America/Indiana/Marengo": "United States",
  "America/Indiana/Petersburg": "United States",
  "America/Indiana/Tell_City": "United States",
  "America/Indiana/Vevay": "United States",
  "America/Indiana/Vincennes": "United States",
  "America/Indiana/Winamac": "United States",
  "America/North_Dakota/Beulah": "United States",
  "America/North_Dakota/Center": "United States",
  "America/North_Dakota/New_Salem": "United States",
  "America/Menominee": "United States",
  "America/Toronto": "Canada",
  "America/Vancouver": "Canada",
  "America/Edmonton": "Canada",
  "America/Winnipeg": "Canada",
  "America/Halifax": "Canada",
  "America/St_Johns": "Canada",
  "America/Regina": "Canada",
  "America/Yellowknife": "Canada",
  "America/Iqaluit": "Canada",
  "America/Moncton": "Canada",
  "America/Thunder_Bay": "Canada",
  "America/Whitehorse": "Canada",
  "America/Dawson": "Canada",
  "America/Dawson_Creek": "Canada",
  "America/Fort_Nelson": "Canada",
  "America/Creston": "Canada",
  "America/Rankin_Inlet": "Canada",
  "America/Resolute": "Canada",
  "America/Glace_Bay": "Canada",
  "America/Goose_Bay": "Canada",
  "America/Blanc-Sablon": "Canada",
  "America/Cambridge_Bay": "Canada",
  "America/Inuvik": "Canada",
  "America/Atikokan": "Canada",
  "America/Nipigon": "Canada",
  "America/Pangnirtung": "Canada",
  "America/Rainy_River": "Canada",
  "America/Swift_Current": "Canada",
  "America/Mexico_City": "Mexico",
  "America/Cancun": "Mexico",
  "America/Merida": "Mexico",
  "America/Monterrey": "Mexico",
  "America/Matamoros": "Mexico",
  "America/Mazatlan": "Mexico",
  "America/Chihuahua": "Mexico",
  "America/Ojinaga": "Mexico",
  "America/Hermosillo": "Mexico",
  "America/Tijuana": "Mexico",
  "America/Bahia_Banderas": "Mexico",

  // Central America & Caribbean
  "America/Guatemala": "Guatemala",
  "America/Belize": "Belize",
  "America/El_Salvador": "El Salvador",
  "America/Tegucigalpa": "Honduras",
  "America/Managua": "Nicaragua",
  "America/Costa_Rica": "Costa Rica",
  "America/Panama": "Panama",
  "America/Havana": "Cuba",
  "America/Jamaica": "Jamaica",
  "America/Port-au-Prince": "Haiti",
  "America/Santo_Domingo": "Dominican Republic",
  "America/Puerto_Rico": "Puerto Rico",
  "America/Nassau": "Bahamas",
  "America/Barbados": "Barbados",
  "America/Martinique": "Martinique",
  "America/Port_of_Spain": "Trinidad and Tobago",
  "America/Curacao": "Curaçao",
  "America/Aruba": "Aruba",
  "America/Grand_Turk": "Turks and Caicos",

  // South America
  "America/Bogota": "Colombia",
  "America/Lima": "Peru",
  "America/Guayaquil": "Ecuador",
  "America/Caracas": "Venezuela",
  "America/La_Paz": "Bolivia",
  "America/Santiago": "Chile",
  "America/Asuncion": "Paraguay",
  "America/Montevideo": "Uruguay",
  "America/Argentina/Buenos_Aires": "Argentina",
  "America/Argentina/Cordoba": "Argentina",
  "America/Argentina/Mendoza": "Argentina",
  "America/Sao_Paulo": "Brazil",
  "America/Rio_Branco": "Brazil",
  "America/Manaus": "Brazil",
  "America/Belem": "Brazil",
  "America/Fortaleza": "Brazil",
  "America/Recife": "Brazil",
  "America/Bahia": "Brazil",
  "America/Cuiaba": "Brazil",
  "America/Campo_Grande": "Brazil",
  "America/Porto_Velho": "Brazil",
  "America/Boa_Vista": "Brazil",
  "America/Noronha": "Brazil",
  "America/Araguaina": "Brazil",
  "America/Maceio": "Brazil",
  "America/Santarem": "Brazil",
  "America/Eirunepe": "Brazil",
  "America/Cayenne": "French Guiana",
  "America/Paramaribo": "Suriname",
  "America/Guyana": "Guyana",

  // Europe
  "Europe/London": "United Kingdom",
  "Europe/Dublin": "Ireland",
  "Europe/Paris": "France",
  "Europe/Berlin": "Germany",
  "Europe/Madrid": "Spain",
  "Europe/Rome": "Italy",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Brussels": "Belgium",
  "Europe/Zurich": "Switzerland",
  "Europe/Vienna": "Austria",
  "Europe/Lisbon": "Portugal",
  "Europe/Stockholm": "Sweden",
  "Europe/Oslo": "Norway",
  "Europe/Copenhagen": "Denmark",
  "Europe/Helsinki": "Finland",
  "Europe/Warsaw": "Poland",
  "Europe/Prague": "Czech Republic",
  "Europe/Budapest": "Hungary",
  "Europe/Bucharest": "Romania",
  "Europe/Sofia": "Bulgaria",
  "Europe/Athens": "Greece",
  "Europe/Istanbul": "Turkey",
  "Europe/Moscow": "Russia",
  "Europe/Kiev": "Ukraine",
  "Europe/Kyiv": "Ukraine",
  "Europe/Minsk": "Belarus",
  "Europe/Vilnius": "Lithuania",
  "Europe/Riga": "Latvia",
  "Europe/Tallinn": "Estonia",
  "Europe/Belgrade": "Serbia",
  "Europe/Zagreb": "Croatia",
  "Europe/Ljubljana": "Slovenia",
  "Europe/Bratislava": "Slovakia",
  "Europe/Luxembourg": "Luxembourg",
  "Europe/Malta": "Malta",
  "Europe/Monaco": "Monaco",
  "Europe/Andorra": "Andorra",
  "Europe/Tirane": "Albania",
  "Europe/Sarajevo": "Bosnia and Herzegovina",
  "Europe/Podgorica": "Montenegro",
  "Europe/Skopje": "North Macedonia",
  "Europe/Chisinau": "Moldova",
  "Atlantic/Reykjavik": "Iceland",

  // Middle East
  "Asia/Dubai": "United Arab Emirates",
  "Asia/Riyadh": "Saudi Arabia",
  "Asia/Qatar": "Qatar",
  "Asia/Bahrain": "Bahrain",
  "Asia/Kuwait": "Kuwait",
  "Asia/Muscat": "Oman",
  "Asia/Jerusalem": "Israel",
  "Asia/Tel_Aviv": "Israel",
  "Asia/Amman": "Jordan",
  "Asia/Beirut": "Lebanon",
  "Asia/Damascus": "Syria",
  "Asia/Baghdad": "Iraq",
  "Asia/Tehran": "Iran",
  "Asia/Aden": "Yemen",

  // Africa
  "Africa/Cairo": "Egypt",
  "Africa/Lagos": "Nigeria",
  "Africa/Nairobi": "Kenya",
  "Africa/Johannesburg": "South Africa",
  "Africa/Casablanca": "Morocco",
  "Africa/Algiers": "Algeria",
  "Africa/Tunis": "Tunisia",
  "Africa/Tripoli": "Libya",
  "Africa/Accra": "Ghana",
  "Africa/Abidjan": "Ivory Coast",
  "Africa/Dakar": "Senegal",
  "Africa/Addis_Ababa": "Ethiopia",
  "Africa/Dar_es_Salaam": "Tanzania",
  "Africa/Kampala": "Uganda",
  "Africa/Khartoum": "Sudan",
  "Africa/Maputo": "Mozambique",
  "Africa/Lusaka": "Zambia",
  "Africa/Harare": "Zimbabwe",
  "Africa/Windhoek": "Namibia",
  "Africa/Gaborone": "Botswana",
  "Africa/Kinshasa": "DR Congo",
  "Africa/Lubumbashi": "DR Congo",
  "Africa/Douala": "Cameroon",

  // South & Southeast Asia
  "Asia/Kolkata": "India",
  "Asia/Calcutta": "India",
  "Asia/Colombo": "Sri Lanka",
  "Asia/Karachi": "Pakistan",
  "Asia/Dhaka": "Bangladesh",
  "Asia/Kathmandu": "Nepal",
  "Asia/Yangon": "Myanmar",
  "Asia/Bangkok": "Thailand",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "Asia/Saigon": "Vietnam",
  "Asia/Jakarta": "Indonesia",
  "Asia/Makassar": "Indonesia",
  "Asia/Jayapura": "Indonesia",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Singapore": "Singapore",
  "Asia/Manila": "Philippines",
  "Asia/Phnom_Penh": "Cambodia",
  "Asia/Vientiane": "Laos",

  // East Asia
  "Asia/Tokyo": "Japan",
  "Asia/Seoul": "South Korea",
  "Asia/Shanghai": "China",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Taipei": "Taiwan",
  "Asia/Macau": "Macau",
  "Asia/Ulaanbaatar": "Mongolia",

  // Central Asia & Caucasus
  "Asia/Almaty": "Kazakhstan",
  "Asia/Tashkent": "Uzbekistan",
  "Asia/Bishkek": "Kyrgyzstan",
  "Asia/Dushanbe": "Tajikistan",
  "Asia/Ashgabat": "Turkmenistan",
  "Asia/Tbilisi": "Georgia",
  "Asia/Yerevan": "Armenia",
  "Asia/Baku": "Azerbaijan",
  "Asia/Kabul": "Afghanistan",

  // Oceania
  "Australia/Sydney": "Australia",
  "Australia/Melbourne": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Perth": "Australia",
  "Australia/Adelaide": "Australia",
  "Australia/Hobart": "Australia",
  "Australia/Darwin": "Australia",
  "Australia/Canberra": "Australia",
  "Australia/Lord_Howe": "Australia",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Chatham": "New Zealand",
  "Pacific/Fiji": "Fiji",
  "Pacific/Guam": "Guam",
  "Pacific/Port_Moresby": "Papua New Guinea",
  "Pacific/Tongatapu": "Tonga",
  "Pacific/Apia": "Samoa",
};

/**
 * Get country name from an IANA timezone string.
 * Returns undefined if the timezone is not recognized.
 */
export function getCountryFromTimezone(timezone: string | null | undefined): string | undefined {
  if (!timezone) return undefined;
  return timezoneToCountry[timezone];
}
